### PR TITLE
fix: isolate extract price for diffrent symbols

### LINKED ISSUE #474: [oracle-node] Fix isolation of processing price in fetchers
- [x] check list for creating new `Fetchers`

### PR DESCRIPTION
**Pull request by koonopek**
In some cases it might seem that nothing can fail in the try/catch block, however, I think it is better to leave it there now, then count that when someone will be updated given fetcher (and introduce change that can fail), he will remember to add try/catch block.
Closes #474

### CODE REVIEW

File: packages/oracle-node/src/fetchers/DexFetcher.ts [hunk 1]
```diff
@@ -72,25 +73,31 @@ export class DexFetcher extends BaseFetcher {
...
-        const reserve0 = parseFloat(pair.reserve0);
-        const reserve1 = parseFloat(pair.reserve1);
-        const reserveUSD = parseFloat(pair.reserveUSD);
-
-        if (symbol0 === currentAssetId) {
-          pricesObj[currentAssetId] = reserveUSD / (2 * reserve0);
-        } else if (symbol1 === currentAssetId) {
-          pricesObj[currentAssetId] = reserveUSD / (2 * reserve1);
+      try {
+        const pairId = this.symbolToPairIdObj[currentAssetId];
```
Comment (hatskier) [inline packages/oracle-node/src/fetchers/DexFetcher.ts:77]: What do you think about moving the code inside the `try` block into a separate function?

**Review by hatskier — COMMENTED** [review]
Refactoring idea to discuss: we can create a function (similar to forEach) e.g. `extractSafelyForEach` to reduce amount of duplicated code (catch blocks with error logging)

File: packages/oracle-node/src/fetchers/DexFetcher.ts (hunk 1 above)
Comment (koonopek) [reply packages/oracle-node/src/fetchers/DexFetcher.ts:77]: Good idea

**Comment by koonopek** [comment]
> Refactoring idea to discuss: we can create a function (similar to forEach) e.g. extractSafelyForEach to reduce amount of duplicated code (catch blocks with error logging). This function can work exactly as forEach, but also can wrap each iteration into try .. catch block

Yes, we can do it, however, if we want to log error with a proper message, we will also have to pass a function that will extract symbol from "thing" that we are iterating because the "thing" is not always pure id it is sometimes object.  But let's try it!

@hatskier

File: packages/oracle-node/src/fetchers/BaseFetcher.ts [hunk 2]
```diff
@@ -95,4 +96,24 @@ export abstract class BaseFetcher implements Fetcher {
     }
     return prices;
   }
+
+  protected extractSafelyForEach<T>(
```
Comment (koonopek) [inline packages/oracle-node/src/fetchers/BaseFetcher.ts:100]: Here is implementation

File: packages/oracle-node/src/fetchers/DexFetcher.ts [hunk 3]
```diff
@@ -69,32 +71,38 @@ export class DexFetcher extends BaseFetcher {
   }
 
   extractPrices(response: DexFetcherResponse, assetIds: string[]): PricesObj {
-    const pricesObj: PricesObj = {};
-
-    for (const currentAssetId of assetIds) {
-      const pairId = this.symbolToPairIdObj[currentAssetId];
-      const pair = response.data.pairs.find((pair) => pair.id === pairId);
+    return this.extractSafelyForEach(
```
Comment (koonopek) [inline packages/oracle-node/src/fetchers/DexFetcher.ts:74]: Example usage,  I haven't implemented it for all fetchers yet, WDYT?

File: packages/oracle-node/src/fetchers/BaseFetcher.ts [hunk 4]
```diff
@@ -95,4 +96,24 @@ export abstract class BaseFetcher implements Fetcher {
...
+    items: T[],
+    setPriceFn: (item: T, pricesObj: PricesObj) => void,
```
Comment (hatskier) [inline packages/oracle-node/src/fetchers/BaseFetcher.ts:102]: Does this function really need the `pricesObj: PricesObj` argument?

Comment (koonopek) [reply packages/oracle-node/src/fetchers/BaseFetcher.ts:102]: Yeah that was my first implementation however it doesn't cover all cases, for example CCXTFetcher
```js
    let pairSymbol = ticker.symbol;
    pairSymbol = this.serializePairSymbol(pairSymbol);
    const lastPrice = ticker.last as number;
    if (pairSymbol.endsWith("/USD")) {
      pricesObj[pairSymbol] = lastPrice;
    } else {
      if (!pricesObj[pairSymbol]) {
        const lastUsdInStablePrice = this.getStableCoinPrice(pairSymbol);
        if (lastUsdInStablePrice) {
          pricesObj[pairSymbol] = lastPrice * lastUsdInStablePrice;
        }
      }
    }
```
Pass function sometimes need access to PricesObject

Comment (koonopek) [reply packages/oracle-node/src/fetchers/BaseFetcher.ts:102]: However, I think we can merge these two idea, and still pass pricesObj for cases like the one above where it is needed, and still assign to pricesObj in `extractSinglePriceFn`

File: packages/oracle-node/src/fetchers/BaseFetcher.ts [hunk 5]
```diff
@@ -95,4 +96,34 @@ export abstract class BaseFetcher implements Fetcher {
...
+    extractId: (item: T) => string
+  ): PricesObj {
+    const pricesObj: PricesObj = {};
+    for (const item of items) {
+      let id: string = "unknown";
+      try {
+        id = extractId(item);
+        if (!id) {
+          throw Error("Could not extract id from response");
+        }
```
Comment (cehali) [inline packages/oracle-node/src/fetchers/BaseFetcher.ts:112]: Maybe not give the `id` initial value because it could lead to the situation when the `if (!id)` check will return false for the `unknown` value when it should throw an error.

**Comment by koonopek** [comment]
Ohh great catche

Pozdrawiam,
Michał Konopka

pon., 27 mar 2023, 12:17 użytkownik Cezary Haliniarz <
***@***.***> napisał:

File: packages/oracle-node/src/fetchers/BaseFetcher.ts (hunk 5 above)
Comment (koonopek) [reply packages/oracle-node/src/fetchers/BaseFetcher.ts]: Ohh great cache, fixed!

File: packages/oracle-node/src/fetchers/ccxt/CcxtFetcher.ts [hunk 6]
```diff
@@ -51,24 +52,27 @@ export class CcxtFetcher extends BaseFetcher {
   }
 
   extractPrices(response: any): PricesObj {
-    const pricesObj: PricesObj = {};
+    return this.extractPricesSafely(
+      Object.values(response) as Ticker[],
+      (ticker, pricesObj) => this.extractPrice(ticker, pricesObj),
```
Comment (hatskier) [inline packages/oracle-node/src/fetchers/ccxt/CcxtFetcher.ts:57]: Can we just pass `this.extractPrice.bind(this)` instead?

File: packages/oracle-node/src/fetchers/chainlink/ChainlinkFetcher.ts [hunk 7]
```diff
@@ -15,14 +15,16 @@ export class ChainlinkFetcher extends BaseFetcher {
   }
 
   extractPrices(response: any): PricesObj {
-    const pricesObj: PricesObj = {};
+    return this.extractPricesSafely(
+      Object.keys(response),
```
Comment (hatskier) [inline packages/oracle-node/src/fetchers/chainlink/ChainlinkFetcher.ts:19]: Shouldn't we pass ids here?

File: packages/oracle-node/src/fetchers/BaseFetcher.ts [hunk 8]
```diff
@@ -95,4 +96,34 @@ export abstract class BaseFetcher implements Fetcher {
     }
     return prices;
   }
+
+  protected extractPricesSafely<T>(
+    items: T[],
+    extractPriceFn: (item: T, pricesObj: PricesObj) => number | undefined,
+    extractId: (item: T) => string
```
Comment (hatskier) [inline packages/oracle-node/src/fetchers/BaseFetcher.ts:103]: Let's call it `extractIdFn` to be consistent with `extractPriceFn`. Also, what do you think about passing here a default implementation (`(id) => id`)?

File: packages/oracle-node/src/fetchers/BaseFetcher.ts [hunk 9]
```diff
@@ -95,4 +96,34 @@ export abstract class BaseFetcher implements Fetcher {
...
+  ): PricesObj {
+    const pricesObj: PricesObj = {};
+    for (const item of items) {
+      let id;
+      try {
+        id = extractId(item);
+        if (!id) {
+          throw Error("Could not extract id from response");
+        }
+        const price = extractPriceFn(item, pricesObj);
```
[the remark this answers is not in the document]
Comment (koonopek) [reply packages/oracle-node/src/fetchers/BaseFetcher.ts:113]: Yes, I answered it here: https://github.com/redstone-finance/redstone-oracles-monorepo/pull/476#discussion_r1147176135, maybe if we could try to change the underlying implementation  of cctx fetcher, however i don't got what is the cons of passing pricesObj

File: packages/oracle-node/src/fetchers/ccxt/CcxtFetcher.ts (hunk 6 above)
Comment (koonopek) [reply packages/oracle-node/src/fetchers/ccxt/CcxtFetcher.ts:57]: yep

File: packages/oracle-node/src/fetchers/chainlink/ChainlinkFetcher.ts (hunk 7 above)
Comment (koonopek) [reply packages/oracle-node/src/fetchers/chainlink/ChainlinkFetcher.ts:19]: Don't get it, seems okey for me, same as with previous implemnetation

File: packages/oracle-node/src/fetchers/BaseFetcher.ts (hunk 9 above)
[the remark this answers is not in the document]
Comment (hatskier) [reply packages/oracle-node/src/fetchers/BaseFetcher.ts:113]: The only con I can see is that it's unclear what is happening with pricesObj after passing it to the function. AFAIU it is used only to read data, but technically it can be modified by the `extractPriceFn` function and it will be different to debug it

File: packages/oracle-node/src/fetchers/BaseFetcher.ts [hunk 10]
```diff
@@ -95,4 +96,34 @@ export abstract class BaseFetcher implements Fetcher {
...
+    for (const item of items) {
+      let id;
+      try {
+        id = extractIdFn(item);
+        if (!id) {
+          throw Error("Could not extract id from response");
+        }
+        const price = extractPriceFn(item, pricesObj);
+
+        if (price) {
```
Comment (hatskier) [inline packages/oracle-node/src/fetchers/BaseFetcher.ts:115]: What about 0 values? Shouldn't we also save them to pricesObj?

File: packages/oracle-node/src/fetchers/BaseFetcher.ts [hunk 11]
```diff
@@ -95,4 +96,34 @@ export abstract class BaseFetcher implements Fetcher {
...
+    extractPriceFn: (item: T, pricesObj: PricesObj) => number | undefined,
+    extractIdFn: (item: T) => string
+  ): PricesObj {
+    const pricesObj: PricesObj = {};
+    for (const item of items) {
+      let id;
+      try {
+        id = extractIdFn(item);
+        if (!id) {
+          throw Error("Could not extract id from response");
```
Comment (hatskier) [inline packages/oracle-node/src/fetchers/BaseFetcher.ts:111]: Shouldn't we add the `new` keyword? (`throw new Error(...`)

File: packages/oracle-node/src/fetchers/BaseFetcher.ts [hunk 12]
```diff
@@ -95,4 +96,34 @@ export abstract class BaseFetcher implements Fetcher {
...
+        }
+        const price = extractPriceFn(item, pricesObj);
+
+        if (price) {
+          pricesObj[id] = price;
+        } else {
+          throw Error("Could not extract price from response");
```
Comment (hatskier) [inline packages/oracle-node/src/fetchers/BaseFetcher.ts:118]: Shouldn't we add the `new` keyword? (`throw new Error(...`)

File: packages/oracle-node/src/fetchers/BaseFetcher.ts (hunk 10 above)
Comment (koonopek) [reply packages/oracle-node/src/fetchers/BaseFetcher.ts:115]: Uhh perfect catch, however it is copied code, so I will change underlying business logic of extracting prices

File: packages/oracle-node/src/fetchers/BaseFetcher.ts (hunk 8 above)
Comment (koonopek) [reply packages/oracle-node/src/fetchers/BaseFetcher.ts]: @hatskier WDYT?

File: packages/oracle-node/src/fetchers/BaseFetcher.ts (hunk 9 above)
[the remark this answers is not in the document]
Comment (koonopek) [reply packages/oracle-node/src/fetchers/BaseFetcher.ts:113]: Same as `forEach` the third parameter :) https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach#parameters However I get the argument, it is okay for me to go with such an implementation.

File: packages/oracle-node/src/fetchers/BaseFetcher.ts [hunk 13]
```diff
@@ -95,4 +100,51 @@ export abstract class BaseFetcher implements Fetcher {
...
+   * Function used to map items to pricesObj. Errors between extracts are isolated.
+   * @param items list of objects that price and id will be extracted from
+   * @param extractPricePairFn this function should extract price pair from item.
+   *  If any of return values will be undefined or function wil throw, price pair
+   * will not be added to result.
+   * @returns pricesObj
+   */
+  protected extractPricesSafely<T>(
+    items: T[],
+    extractPricePairFn: ExtractPricePairFn<T>
```
Comment (koonopek) [inline packages/oracle-node/src/fetchers/BaseFetcher.ts:114]: Change implementation to return {id, price} obj, thus no additional function is needed and the code is easier to read.

File: packages/oracle-node/src/fetchers/BaseFetcher.ts [hunk 14]
```diff
@@ -1,8 +1,13 @@
 import { Consola } from "consola";
 import { Fetcher, PriceDataFetched, FetcherOpts, PricesObj } from "../types";
+import { stringifyError } from "../utils/error-stringifier";
 import createLogger from "../utils/logger";
+import { isDefined } from "../utils/objects";
 
 const MAX_RESPONSE_TIME_TO_RETRY_FETCHING_MS = 3000;
+export type ExtractPricePairFn<T> = (
+  item: T
```
Comment (koonopek) [inline packages/oracle-node/src/fetchers/BaseFetcher.ts:9]: Remove passing pricesObj

File: packages/oracle-node/src/fetchers/BaseFetcher.ts [hunk 15]
```diff
@@ -1,8 +1,13 @@
...
+) => { id?: string; price?: number } | undefined;
```
Comment (hatskier) [inline packages/oracle-node/src/fetchers/BaseFetcher.ts:10]: Let's remove `?s` from id and price and `| undefined`, but still have validation (in runtime) in BaseFetcher

**Review by hatskier — APPROVED** [review]
Great job!
